---
title: Cherry Winkle Moore
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  gallery:
    title: Gallery
    output: true
  authors:
    title: Authors
    output: true
permalink: "/:year/:month/:title/"
email: artist@cherrywinklemoore.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: https://github.cherrywinklemoore.com
author: cherrywinklemoore
logo: /favicon.ico
lang: en_US
favicon: /favicon.ico
og_image: /assets/images/bg-hero.jpg
# twitter_username: 
# github_username: 
plugins:
  - jekyll-feed
  - jekyll-strapi
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
gems:
  - jekyll-paginate-v2
include:
  - _uploads
  - _pages
exclude:
  - ".sass-cache/"
  - ".jekyll-cache/"
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
strapi:
  endpoint: http://localhost:1337
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
cloudinary:
  cloud_name: cherrywinklemoore-com
  only_prod: true
  verbose: false
  presets:
    default:
      gravity: auto
      crop: fill
      focus: auto
      min_width: 256
      max_width: 1024
      figure: never
      attributes:
        class: img-fluid mb-2 mt-3 w-100
        loading: lazy
compress_html:
  clippings: all
  comments:
    - '<!-- '
    - ' -->'
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []
pagination:
  enabled: false
  per_page: 9
  permalink: '/page-:num/'
  title: ':title'
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: false
  categories:
    layouts:
      - autopage.html
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    slugify:
      mode: default
      case: true
  tags:
    layouts:
      - autopage.html
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    slugify:
      mode: default
      case: true
  collections:
    layouts:
      - autopage.html
    title: 'Posts in collection :coll'
    permalink: '/collection/:coll'
    slugify:
      mode: default
      case: true
defaults:
  - scope:
      path: ''
    values:
      layout: page
      author: cherrywinklemoore
  - scope:
      path: ''
      type: posts
    values:
      layout: blog-single
      is_post: true
  - scope:
      path: _pages
    values:
      layout: page
      permalink: '/:basename'
  - scope:
      path: ''
      type: authors
    values:
      layout: blog-author
  - scope:
      path: _gallery
    values:
      layout: shop-single