---
title: Cherry Winkle Moore
timezone: UTC
permalink: /:year/:month/:title/
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  shop:
    title: shop
    output: true
email: artist@cherrywinklemoore.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: https://github.cherrywinklemoore.com
twitter_username: 
github_username: 
theme: minima
plugins:
- jekyll-feed
- jekyll-strapi
include:
- _uploads
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
strapi:
  endpoint: http://localhost:1337
