title: Cherry Winkle Moore
timezone: UTC
sass:
  quiet_deps: true
  style: compressed
  sass_dir: _sass
collections:
  authors:
    title: Authors
    output: true
  gallery:
    title: Gallery
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
  pages:
    output: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: blog-single
      author: cherrywinklemoore
      image:
      comments: true
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      # permalink: "/:basename"
      image: "/assets/images/bg-altered-book-2-e1424183399895.jpg"
  - scope:
      path: ""
      type: authors
    values:
      layout: blog-author
      image: "/assets/images/bg-altered-book-2-e1424183399895.jpg"
  - scope:
      path: ""
      type: gallery
    values:
      layout: shop-single
      image:
      status: For Sale
      medium: Oil on canvas
      data-item-price: 0.0
      data-item-weight: 1000
      data-item-length: 50
      data-item-width: 50
      data-item-height: 4
      data-item-quantity: 1
      data-item-max-quantity: 1
      data-item-stackable: false
baseurl: ""
url: https://www.cherrywinklemoore.com
permalink: "/:year/:month/:title/"
email: artist@cherrywinklemoore.com
description: Cherry Winkle Moore is a visual artist and retured hospice chaplain in
  Bryan Texas.
author: cherrywinklemoore
logo: "/assets/favicons/favicon.ico"
favicon: "/assets/favicons/favicon.ico"
og_image: "/assets/images/bg-altered-book-2-e1424183399895.jpg"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
gems:
  - jekyll-paginate-v2
compress_html:
  clippings: all
  comments:
    - "<!-- "
    - " -->"
  endings:
    - html
    - head
    - body
    - li
    - dt
    - dd
    - rt
    - rp
    - optgroup
    - option
    - colgroup
    - caption
    - thead
    - tbody
    - tfoot
    - tr
    - td
    - th
  profile: false
  blanklines: false
  ignore:
    envs: []
pagination:
  enabled: true
  debug: false
  per_page: 9
  permalink: "/page-:num.html"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
autopages:
  enabled: true
  categories:
    layouts:
      - autopage.html
    title: Posts in category :cat
    permalink: "/category/:cat"
    slugify:
      mode: default
      case: true
  tags:
    layouts:
      - autopage.html
    title: Posts tagged with :tag
    permalink: "/tag/:tag"
    slugify:
      mode: default
      case: true
  collections:
    layouts:
      - autopage.html
    title: Posts in collection :coll
    permalink: "/collection/:coll"
    slugify:
      mode: default
      case: true
