# Workflow to build and deploy a Jekyll site to GitHub Pages
name: Deploy Jekyll Site to GitHub Pages

on:
  # Trigger on push to the default branch
  push:
    branches: ["main"]
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

permissions:
  contents: read          # Allows reading repository contents
  pages: write            # Allows writing to GitHub Pages
  id-token: write         # Required for OIDC authentication

concurrency:
  group: "pages-deployment" # Ensures only one deployment runs at a time
  cancel-in-progress: false # Keeps in-progress deployments running

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest # Use the latest stable Ubuntu version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.5"     # Uses the specified Ruby version
          bundler-cache: true       # Caches gems to speed up subsequent builds
          cache-version: 0          # Increment to reset the bundler cache

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build Jekyll Site
        # Outputs to the './_site' directory
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # Explicitly specify the path to the built site

  # Deploy job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
